//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIDA.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class for Ukrainian localization, for looking up localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EngUI_uk
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EngUI_uk()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIDA.Properties.EngUI.uk", typeof(EngUI_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Діагностика.
        /// </summary>
        public static string DiagnosticsTab
        {
            get
            {
                return ResourceManager.GetString("DiagnosticsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не OK.
        /// </summary>
        public static string StatusNotOK
        {
            get
            {
                return ResourceManager.GetString("StatusNotOK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Усі.
        /// </summary>
        public static string All
        {
            get
            {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string SettingsTab
        {
            get
            {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Перевірити оновлення.
        /// </summary>
        public static string CheckForUpdates
        {
            get
            {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Мова.
        /// </summary>
        public static string Language
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Англійська.
        /// </summary>
        public static string English
        {
            get
            {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        public static string Ukrainian
        {
            get
            {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Не вдалося відкрити сторінку оновлень.
        /// </summary>
        public static string UpdateCheckFailed
        {
            get
            {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
    }
}